name: collision_severity_prediction_service

channels:
  - conda-forge
  - defaults

dependencies:
  - fastapi==0.115.5
  - pandas==2.2.3
  - py-xgboost==2.1.2
  - pydantic-settings==2.6.1
  - python==3.13.0
  - scikit-learn==1.5.2
  - uvicorn==0.32.1
